[package]
name = "kai-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = { version = "0.10.2", default-features = false }
serde = { version = "1.0.140", default-features = false }