[package]
name = "kai-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kai-proto= { path = "../proto"}
prost-types = "0.11.1"