[package]
name = "kai-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"kai-proto" = { path = "../proto" }
"prost" = "0.11.0"
"prost-types" = "0.11.1"
"bitvec" = "1"
"num" = "0.4"
"num-derive" = "0.3"
"num-traits" = "0.2"
"mockall" = "0.11.2"
"sha3" = "0.10.4"