[package]
name = "kp-debug-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.10"
syn = "1.0.98"
proc-macro2 = "1.0"

[features]
default = [ "std" ]
std = []
# By default `RuntimeDebug` implements `Debug` that outputs `<wasm:stripped>` when `std` is
# disabled. However, sometimes downstream users need to have the real `Debug` implementation for
# debugging purposes. If this is required, a user only needs to add this crate as a dependency of
# their runtime and enable the `force-debug` feature.
force-debug = []

[dev-dependencies]