[package]
name = "kai-network-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.24"
futures-timer = "3.0.2"
thiserror = "1.0.37"
libp2p = "0.46.1"

kai-network-config = { path = "../config"}