

[package]
name = "kai_proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.10.4"
prost-types = "0.10.1"
bytes = "1.1"
flex-error = "0.4.4"
[build-dependencies]
prost-build = "0.10.4"
walkdir = "2"

[dev-dependencies]
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
