[package]
name = "kai-network-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url         = { version = "2.3.1", default-features = false }
flex-error  = { version = "0.4.4", default-features = false }
toml        = { version = "0.5.9", default-features = false }

# Packages dependencies

[dev-dependencies]
pretty_assertions = "0.7.2"
yaml-rust = "0.4.5"
serde_yaml = "0.9.14"
serde       = { version = "1.0.147", features = ["derive"] }
serde_json  = "1.0.87"