[package]
name = "kp-core-hashing-proc-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.37"
quote = "1.0.6"
syn = { version = "1.0.98", features = ["full", "parsing"] }
kp-core-hashing = { version = "0.1.0", default-features = false, path = "../" }