[package]
name = "kai-consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
"kai-proto" = { path = "../proto" }
"kai-types" = { path = "../types" }
"kai-lib" = { path = "../lib" }
"prost" = "0.11.0"
"thiserror" = "1.0.32"
"anyhow" = "1.0"
"bytes" = { version = "1", features = ["serde"] }
"bitvec" = "1.0.1"
"tokio" = { version = "1.21.2", features = ["full"] }
"async-trait" = "0.1.57"
"ethereum-types" = { version = "0.14", features = ["codec"] }

"log" = "0.4.17"
"env_logger" = "0.9.0"
"mockall" = "0.11.2"

[dev-dependencies]
"tokio-test" = "0.4.2"
