[package]
name = "kai-consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
"kai-proto" = { path = "../proto" }
"kai-types" = { path = "../types" }
"prost" = "0.11.0"
"thiserror" = "1.0.32"
"anyhow" = "1.0"
"bitvec" = "1.0.1"
"tokio" = { version = "1.20.1", features = ["sync"] }

log = "0.4.17"
env_logger = "0.9.0"