[package]
name = "kp-runtime"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }
either = { version = "1.5", default-features = false }
kp-debug-derive = { version = "0.1.0", default-features = false, path = "../debug-derive" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
hash256-std-hasher = { version = "0.15.2", default-features = false }
kp-core = { version = "0.1.0", default-features = false, path = "../core" }
kp-std = { version = "0.1.0", default-features = false, path = "../std" }
serde = { version = "1.0.136", features = ["derive"], optional = true }
kp-io = { version = "0.1.0", default-features = false, path = "../io" }

[dev-dependencies]
rand = "0.7.2"
serde_json = "1.0.85"
zstd = { version = "0.11.2", default-features = false }
kp-tracing = { version = "0.1.0", path = "../tracing" }

[features]
runtime-benchmarks = []
default = ["std"]
std = [
  "codec/std",
	"either/use_std",
  "hash256-std-hasher/std",
  "scale-info/std",
  "serde",
]
