[package]
name = "kai-store"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-util-mem.workspace = true
smallvec.workspace = true
rocksdb.workspace = true
enum-map.workspace = true
strum.workspace = true
strum_macros.workspace = true
tracing.workspace = true
bytesize.workspace = true
rlimit.workspace = true
num_cpus.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tempfile.workspace = true
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
assert_matches.workspace = true
borsh.workspace = true
kai-primitives-core.workspace = true
kvdb.workspace = true
kvdb-rocksdb.workspace = true
parity-db.workspace = true
log.workspace = true
primitive-types= "0.12.0"