[package]
name = "kp-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-util-mem = { version = "0.12.0", default-features = false, features = ["primitive-types"] }
primitive-types = { version = "0.12.0", default-features = false, features = ["codec", "scale-info"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
kp-std = { version = "0.1.0", default-features = false, path = "../std" }
secrecy = { version = "0.8.0", default-features = false }
zeroize = { version = "1.4.3", default-features = false }
kp-core-hashing = { version = "0.1.0", path = "./hashing", default-features = false, optional = true }
base58 = { version = "0.2.0", optional = true }
rand = { version = "0.7.3", optional = true, features = ["small_rng"] }
regex = { version = "1.5.4", optional = true }
substrate-bip39 = { version = "0.4.4", optional = true }
tiny-bip39 = { version = "0.8.2", optional = true }
blake2 = { version = "0.10.4", default-features = false, optional = true }
thiserror = { version = "1.0.30", optional = true }
lazy_static = { version = "1.4.0", default-features = false, optional = true }
serde = { version = "1.0.136", optional = true, features = ["derive"] }
kp-serializer = { path = "../serializer"}
kp-storage = { version = "0.1.0", default-features = false, path = "../storage" }

# full crypto
array-bytes = { version = "4.1", optional = true }
ss58-registry = { version = "1.29.0", default-features = false }
libsecp256k1 = { version = "0.7", default-features = false, features = ["static-context"], optional = true }
merlin = { version = "2.0", default-features = false, optional = true }
secp256k1 = { version = "0.24.0", default-features = false, features = ["recovery", "alloc"], optional = true }
hash256-std-hasher = { version = "0.15.2", default-features = false }
hash-db = { version = "0.15.2", default-features = false }

[dev-dependencies]
serde_json = "1.0"
kp-core-hashing-proc-macro = { version = "0.1.0", path = "./hashing/proc-macro" }

[features]
default = ["std"]
std = [
	"kp-core-hashing",
	"base58",
	"substrate-bip39",
	"tiny-bip39",
	"rand",
	"serde",
	"thiserror",
	"regex",
	"secrecy/alloc",
	"blake2/std",
	"full_crypto",
	"lazy_static",
	"array-bytes",
	"ss58-registry/std",
	"secp256k1/std",
	"secp256k1/global-context",
	"libsecp256k1/std",
	"primitive-types/std",
	"primitive-types/serde",
	"primitive-types/byteorder",
	"primitive-types/rustc-hex",
]
# This feature enables all crypto primitives for `no_std` builds like microcontrollers
# or Intel SGX.
# For the regular wasm runtime builds this should not be used.
full_crypto = [
	"kp-core-hashing",
	"blake2",
	"array-bytes",
]