[package]
name = "kai-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kai-store = {path = "../store"}
flex-error = "0.4.4"
serde = "1.0.147"
subtle = "2.4.1"
subtle-encoding = "0.5.1"