[package]
name = "kardia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.145", default-features = false }
sha2 = { version = "0.10.6", default-features = false }
subtle = { version = "2.4.1", default-features = false }
subtle-encoding = { version = "0.5.1", default-feature = false }
flex-error = { version = "0.4.4", default-features = false }
ed25519-consensus = { version = "2.0.1", default-features = false }
serde_json = { version = "1", default-features = false, features = ["alloc"] }