[package]
name = "kai-p2p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = { version = "0.7", default-features = false, features = [
  "codegen",
  "prost",
  "transport",
] }
primitive-types = "0.11.1"
secp256k1 = "0.24.0"
ed25519-consensus   = { version = "2.0.1",  default-features = false }
ed25519-dalek = { version="1.0.1" } 
flume = {version = "0.10.14" }
