[package]
name = "kai-p2p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p256 = { version = "0.11.1", features = ["ecdh"]}
secp256k1 = "0.24.1"

aead                = { version = "0.4",  default-features = false }
async-trait         = { version = "0.1",  default-features = false }
chacha20poly1305    = { version = "0.8",  default-features = false, features = [ "reduced-round" ] }
ed25519-consensus   = { version = "1.2",  default-features = false }
eyre                = { version = "0.6",  default-features = false }
flex-error          = { version = "0.4",  default-features = false }
flume               = { version = "0.10", default-features = false }
futures-core        = { version = "0.3",  default-features = false, features = [ "alloc" ] }
hkdf                = { version = "0.10", default-features = false }
merlin              = { version = "2.0",  default-features = false }
prost               = { version = "0.10", default-features = false }
rand_core           = { version = "0.5",  default-features = false, features = [ "std" ] }
sha2                = { version = "0.9",  default-features = false }
signature           = { version = "1.3",  default-features = false }
subtle              = { version = "2.0",  default-features = false }
x25519-dalek        = { version = "1.1",  default-features = false, features = [ "u64_backend" ] }
zeroize             = { version = "1.0",  default-features = false }
k256                = { version = "0.11.6", default-features = false, features = [ "ecdsa", "ecdsa-core" ] }

# path dependencies
# tendermint          = { version = "0.24.0-pre.1", default-features = false, path = "../tendermint" }
# tendermint-proto    = { version = "0.24.0-pre.1", default-features = false, path = "../proto" }
# tendermint-std-ext  = { version = "0.24.0-pre.1", default-features = false, path = "../std-ext" }
kai_proto           = { path = "../proto"}
kai-std-ext         = { path = "../std-ext"}
kai-core            = { path = "../core"}

# optional dependencies
prost-derive        = { version = "0.10", optional = true }

