[package]
name = "kp-io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
kp-core = { path = "../core"}
futures = { version = "0.3.21", features = ["thread-pool"], optional = true }


[features]
default = [ "std" ]
std = [ "futures" ]