[package]
name = "kp-runtime-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
kp-std = { version = "0.1.0", default-features = false, path = "../std" }
kp-tracing = { version = "0.1.0", default-features = false, path = "../tracing" }
kp-externalities = { version = "0.1.0", default-features = false, path = "../externalities" }
codec = { package = "parity-scale-codec", version = "3.1.3", default-features = false, features = ["bytes"] }

[features]
default = [ "std", "kp-std/std",  "kp-tracing/std", "kp-externalities/std", "codec/std"]
std = []