[package]
name = "kai-bloom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bv = { version = "0.11.1", features = ["serde"] }
fnv = "1.0.7"
log = "0.4.17"
rand = "0.8.5"
rayon = "1.5.3"
serde = { version = "1.0.144", features = ["rc"] }
serde_derive = "1.0.103"
kp-core = { path = "../core"}