[package]
name = "kai_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p256 = { version = "0.11.1", features = ["ecdsa-core", "arithmetic"] }
hex = { version = "0.4.3" }
secp256k1 = { version = "0.24.0" }
elliptic-curve = { version = "0.12.3"}
